// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package stock;

/**
 * Protobuf enum {@code stock.currency}
 */
public enum currency
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PLN = 1;</code>
   */
  PLN(1),
  /**
   * <code>EUR = 2;</code>
   */
  EUR(2),
  /**
   * <code>CHF = 3;</code>
   */
  CHF(3),
  /**
   * <code>USD = 4;</code>
   */
  USD(4),
  /**
   * <code>GBP = 5;</code>
   */
  GBP(5),
  ;

  /**
   * <code>PLN = 1;</code>
   */
  public static final int PLN_VALUE = 1;
  /**
   * <code>EUR = 2;</code>
   */
  public static final int EUR_VALUE = 2;
  /**
   * <code>CHF = 3;</code>
   */
  public static final int CHF_VALUE = 3;
  /**
   * <code>USD = 4;</code>
   */
  public static final int USD_VALUE = 4;
  /**
   * <code>GBP = 5;</code>
   */
  public static final int GBP_VALUE = 5;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static currency valueOf(int value) {
    return forNumber(value);
  }

  public static currency forNumber(int value) {
    switch (value) {
      case 1: return PLN;
      case 2: return EUR;
      case 3: return CHF;
      case 4: return USD;
      case 5: return GBP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<currency>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      currency> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<currency>() {
          public currency findValueByNumber(int number) {
            return currency.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return stock.Stock.getDescriptor().getEnumTypes().get(0);
  }

  private static final currency[] VALUES = values();

  public static currency valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private currency(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:stock.currency)
}

