// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package stock;

public interface currencyDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stock.currencyData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .stock.currency curr = 1;</code>
   */
  boolean hasCurr();
  /**
   * <code>required .stock.currency curr = 1;</code>
   */
  stock.currency getCurr();

  /**
   * <code>required double value = 2;</code>
   */
  boolean hasValue();
  /**
   * <code>required double value = 2;</code>
   */
  double getValue();
}
