// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package stock;

public interface stockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stock.stockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .stock.currencyData currencies = 1;</code>
   */
  java.util.List<stock.currencyData> 
      getCurrenciesList();
  /**
   * <code>repeated .stock.currencyData currencies = 1;</code>
   */
  stock.currencyData getCurrencies(int index);
  /**
   * <code>repeated .stock.currencyData currencies = 1;</code>
   */
  int getCurrenciesCount();
  /**
   * <code>repeated .stock.currencyData currencies = 1;</code>
   */
  java.util.List<? extends stock.currencyDataOrBuilder> 
      getCurrenciesOrBuilderList();
  /**
   * <code>repeated .stock.currencyData currencies = 1;</code>
   */
  stock.currencyDataOrBuilder getCurrenciesOrBuilder(
      int index);
}
