// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currencyStatus.proto

package currencyProvider;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:currencyProvider.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool pln = 1;</code>
   */
  boolean getPln();

  /**
   * <code>bool usd = 2;</code>
   */
  boolean getUsd();

  /**
   * <code>bool eur = 3;</code>
   */
  boolean getEur();

  /**
   * <code>bool gbp = 4;</code>
   */
  boolean getGbp();
}
