// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package stock;

/**
 * Protobuf type {@code stock.stockResponse}
 */
public  final class stockResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:stock.stockResponse)
    stockResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use stockResponse.newBuilder() to construct.
  private stockResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private stockResponse() {
    updatedCurrencies_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private stockResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              updatedCurrencies_ = new java.util.ArrayList<stock.currencyData>();
              mutable_bitField0_ |= 0x00000001;
            }
            updatedCurrencies_.add(
                input.readMessage(stock.currencyData.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        updatedCurrencies_ = java.util.Collections.unmodifiableList(updatedCurrencies_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return stock.Stock.internal_static_stock_stockResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return stock.Stock.internal_static_stock_stockResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            stock.stockResponse.class, stock.stockResponse.Builder.class);
  }

  public static final int UPDATEDCURRENCIES_FIELD_NUMBER = 1;
  private java.util.List<stock.currencyData> updatedCurrencies_;
  /**
   * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
   */
  public java.util.List<stock.currencyData> getUpdatedCurrenciesList() {
    return updatedCurrencies_;
  }
  /**
   * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
   */
  public java.util.List<? extends stock.currencyDataOrBuilder> 
      getUpdatedCurrenciesOrBuilderList() {
    return updatedCurrencies_;
  }
  /**
   * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
   */
  public int getUpdatedCurrenciesCount() {
    return updatedCurrencies_.size();
  }
  /**
   * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
   */
  public stock.currencyData getUpdatedCurrencies(int index) {
    return updatedCurrencies_.get(index);
  }
  /**
   * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
   */
  public stock.currencyDataOrBuilder getUpdatedCurrenciesOrBuilder(
      int index) {
    return updatedCurrencies_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getUpdatedCurrenciesCount(); i++) {
      if (!getUpdatedCurrencies(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < updatedCurrencies_.size(); i++) {
      output.writeMessage(1, updatedCurrencies_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < updatedCurrencies_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, updatedCurrencies_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof stock.stockResponse)) {
      return super.equals(obj);
    }
    stock.stockResponse other = (stock.stockResponse) obj;

    if (!getUpdatedCurrenciesList()
        .equals(other.getUpdatedCurrenciesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUpdatedCurrenciesCount() > 0) {
      hash = (37 * hash) + UPDATEDCURRENCIES_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatedCurrenciesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static stock.stockResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stock.stockResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stock.stockResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stock.stockResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stock.stockResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stock.stockResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stock.stockResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stock.stockResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static stock.stockResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static stock.stockResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static stock.stockResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stock.stockResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(stock.stockResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code stock.stockResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stock.stockResponse)
      stock.stockResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stock.Stock.internal_static_stock_stockResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stock.Stock.internal_static_stock_stockResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              stock.stockResponse.class, stock.stockResponse.Builder.class);
    }

    // Construct using stock.stockResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUpdatedCurrenciesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (updatedCurrenciesBuilder_ == null) {
        updatedCurrencies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        updatedCurrenciesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return stock.Stock.internal_static_stock_stockResponse_descriptor;
    }

    @java.lang.Override
    public stock.stockResponse getDefaultInstanceForType() {
      return stock.stockResponse.getDefaultInstance();
    }

    @java.lang.Override
    public stock.stockResponse build() {
      stock.stockResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public stock.stockResponse buildPartial() {
      stock.stockResponse result = new stock.stockResponse(this);
      int from_bitField0_ = bitField0_;
      if (updatedCurrenciesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          updatedCurrencies_ = java.util.Collections.unmodifiableList(updatedCurrencies_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.updatedCurrencies_ = updatedCurrencies_;
      } else {
        result.updatedCurrencies_ = updatedCurrenciesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof stock.stockResponse) {
        return mergeFrom((stock.stockResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(stock.stockResponse other) {
      if (other == stock.stockResponse.getDefaultInstance()) return this;
      if (updatedCurrenciesBuilder_ == null) {
        if (!other.updatedCurrencies_.isEmpty()) {
          if (updatedCurrencies_.isEmpty()) {
            updatedCurrencies_ = other.updatedCurrencies_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUpdatedCurrenciesIsMutable();
            updatedCurrencies_.addAll(other.updatedCurrencies_);
          }
          onChanged();
        }
      } else {
        if (!other.updatedCurrencies_.isEmpty()) {
          if (updatedCurrenciesBuilder_.isEmpty()) {
            updatedCurrenciesBuilder_.dispose();
            updatedCurrenciesBuilder_ = null;
            updatedCurrencies_ = other.updatedCurrencies_;
            bitField0_ = (bitField0_ & ~0x00000001);
            updatedCurrenciesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUpdatedCurrenciesFieldBuilder() : null;
          } else {
            updatedCurrenciesBuilder_.addAllMessages(other.updatedCurrencies_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getUpdatedCurrenciesCount(); i++) {
        if (!getUpdatedCurrencies(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      stock.stockResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (stock.stockResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<stock.currencyData> updatedCurrencies_ =
      java.util.Collections.emptyList();
    private void ensureUpdatedCurrenciesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        updatedCurrencies_ = new java.util.ArrayList<stock.currencyData>(updatedCurrencies_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        stock.currencyData, stock.currencyData.Builder, stock.currencyDataOrBuilder> updatedCurrenciesBuilder_;

    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public java.util.List<stock.currencyData> getUpdatedCurrenciesList() {
      if (updatedCurrenciesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(updatedCurrencies_);
      } else {
        return updatedCurrenciesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public int getUpdatedCurrenciesCount() {
      if (updatedCurrenciesBuilder_ == null) {
        return updatedCurrencies_.size();
      } else {
        return updatedCurrenciesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public stock.currencyData getUpdatedCurrencies(int index) {
      if (updatedCurrenciesBuilder_ == null) {
        return updatedCurrencies_.get(index);
      } else {
        return updatedCurrenciesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public Builder setUpdatedCurrencies(
        int index, stock.currencyData value) {
      if (updatedCurrenciesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdatedCurrenciesIsMutable();
        updatedCurrencies_.set(index, value);
        onChanged();
      } else {
        updatedCurrenciesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public Builder setUpdatedCurrencies(
        int index, stock.currencyData.Builder builderForValue) {
      if (updatedCurrenciesBuilder_ == null) {
        ensureUpdatedCurrenciesIsMutable();
        updatedCurrencies_.set(index, builderForValue.build());
        onChanged();
      } else {
        updatedCurrenciesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public Builder addUpdatedCurrencies(stock.currencyData value) {
      if (updatedCurrenciesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdatedCurrenciesIsMutable();
        updatedCurrencies_.add(value);
        onChanged();
      } else {
        updatedCurrenciesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public Builder addUpdatedCurrencies(
        int index, stock.currencyData value) {
      if (updatedCurrenciesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdatedCurrenciesIsMutable();
        updatedCurrencies_.add(index, value);
        onChanged();
      } else {
        updatedCurrenciesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public Builder addUpdatedCurrencies(
        stock.currencyData.Builder builderForValue) {
      if (updatedCurrenciesBuilder_ == null) {
        ensureUpdatedCurrenciesIsMutable();
        updatedCurrencies_.add(builderForValue.build());
        onChanged();
      } else {
        updatedCurrenciesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public Builder addUpdatedCurrencies(
        int index, stock.currencyData.Builder builderForValue) {
      if (updatedCurrenciesBuilder_ == null) {
        ensureUpdatedCurrenciesIsMutable();
        updatedCurrencies_.add(index, builderForValue.build());
        onChanged();
      } else {
        updatedCurrenciesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public Builder addAllUpdatedCurrencies(
        java.lang.Iterable<? extends stock.currencyData> values) {
      if (updatedCurrenciesBuilder_ == null) {
        ensureUpdatedCurrenciesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, updatedCurrencies_);
        onChanged();
      } else {
        updatedCurrenciesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public Builder clearUpdatedCurrencies() {
      if (updatedCurrenciesBuilder_ == null) {
        updatedCurrencies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        updatedCurrenciesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public Builder removeUpdatedCurrencies(int index) {
      if (updatedCurrenciesBuilder_ == null) {
        ensureUpdatedCurrenciesIsMutable();
        updatedCurrencies_.remove(index);
        onChanged();
      } else {
        updatedCurrenciesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public stock.currencyData.Builder getUpdatedCurrenciesBuilder(
        int index) {
      return getUpdatedCurrenciesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public stock.currencyDataOrBuilder getUpdatedCurrenciesOrBuilder(
        int index) {
      if (updatedCurrenciesBuilder_ == null) {
        return updatedCurrencies_.get(index);  } else {
        return updatedCurrenciesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public java.util.List<? extends stock.currencyDataOrBuilder> 
         getUpdatedCurrenciesOrBuilderList() {
      if (updatedCurrenciesBuilder_ != null) {
        return updatedCurrenciesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(updatedCurrencies_);
      }
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public stock.currencyData.Builder addUpdatedCurrenciesBuilder() {
      return getUpdatedCurrenciesFieldBuilder().addBuilder(
          stock.currencyData.getDefaultInstance());
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public stock.currencyData.Builder addUpdatedCurrenciesBuilder(
        int index) {
      return getUpdatedCurrenciesFieldBuilder().addBuilder(
          index, stock.currencyData.getDefaultInstance());
    }
    /**
     * <code>repeated .stock.currencyData updatedCurrencies = 1;</code>
     */
    public java.util.List<stock.currencyData.Builder> 
         getUpdatedCurrenciesBuilderList() {
      return getUpdatedCurrenciesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        stock.currencyData, stock.currencyData.Builder, stock.currencyDataOrBuilder> 
        getUpdatedCurrenciesFieldBuilder() {
      if (updatedCurrenciesBuilder_ == null) {
        updatedCurrenciesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            stock.currencyData, stock.currencyData.Builder, stock.currencyDataOrBuilder>(
                updatedCurrencies_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        updatedCurrencies_ = null;
      }
      return updatedCurrenciesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:stock.stockResponse)
  }

  // @@protoc_insertion_point(class_scope:stock.stockResponse)
  private static final stock.stockResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new stock.stockResponse();
  }

  public static stock.stockResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<stockResponse>
      PARSER = new com.google.protobuf.AbstractParser<stockResponse>() {
    @java.lang.Override
    public stockResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new stockResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<stockResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<stockResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public stock.stockResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

