// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `bank.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public class CreatedAccount implements java.lang.Cloneable,
                                       java.io.Serializable
{
    public AccountPrx account;

    public String pesel;

    public boolean isPremium;

    public CreatedAccount()
    {
        this.pesel = "";
    }

    public CreatedAccount(AccountPrx account, String pesel, boolean isPremium)
    {
        this.account = account;
        this.pesel = pesel;
        this.isPremium = isPremium;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        CreatedAccount r = null;
        if(rhs instanceof CreatedAccount)
        {
            r = (CreatedAccount)rhs;
        }

        if(r != null)
        {
            if(this.account != r.account)
            {
                if(this.account == null || r.account == null || !this.account.equals(r.account))
                {
                    return false;
                }
            }
            if(this.pesel != r.pesel)
            {
                if(this.pesel == null || r.pesel == null || !this.pesel.equals(r.pesel))
                {
                    return false;
                }
            }
            if(this.isPremium != r.isPremium)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Demo::CreatedAccount");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, account);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, pesel);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, isPremium);
        return h_;
    }

    public CreatedAccount clone()
    {
        CreatedAccount c = null;
        try
        {
            c = (CreatedAccount)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeProxy(this.account);
        ostr.writeString(this.pesel);
        ostr.writeBool(this.isPremium);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.account = AccountPrx.uncheckedCast(istr.readProxy());
        this.pesel = istr.readString();
        this.isPremium = istr.readBool();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, CreatedAccount v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public CreatedAccount ice_read(com.zeroc.Ice.InputStream istr)
    {
        CreatedAccount v = new CreatedAccount();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CreatedAccount> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, CreatedAccount v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<CreatedAccount> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(CreatedAccount.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final CreatedAccount _nullMarshalValue = new CreatedAccount();

    public static final long serialVersionUID = -8830811975625058687L;
}
